Resolve possible GSOD when selecting language after flashing
By adding a sanity check by checking if a key does exist

OpenPLi Enigma2 crash log

crashdate=Fri Sep 27 18:50:43 2024
compiledate=Sep 24 2024
skin=PLi-FullNightHD/skin.xml
sourcedate=2024-09-24
branch=develop
rev=5c5f095
component=Enigma2

stbmodel=duo4k
stbmodel=dm8000
kernelcmdline=kexec=1 rootfstype=ext4 rootflags=data=journal rootwait rw coherent_pool=2M vmalloc=500m bmem=891m@1156m bmem=575m@3520m kernel=/linuxrootfs3/zImage root=/dev/mmcblk0p9 rootsubdir=linuxrootfs3
nimsockets=NIM Socket 0:
imageissue=openpli develop %h

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/Renderer/Listbox.py", line 61, in selectionChanged
  File "/usr/lib/enigma2/python/Components/Converter/StringList.py", line 22, in selectionChanged
  File "/usr/lib/enigma2/python/Components/Sources/List.py", line 63, in selectionChanged
  File "/usr/lib/enigma2/python/Screens/Wizard.py", line 448, in selChanged
KeyError: 'evaluatedlist'
[ePyObject] (CallObject(<bound method Listbox.selectionChanged of <Components.Renderer.Listbox.Listbox object at 0xb18f63a0>>,()) failed)

(cherry picked from commit 6682280a7ec7751421ee013312eb946b6b46f0e2)