Fix the mess (Emergency) (#3019)
* Revert "enigma2: fx build with musl (#3014)"

It's a patch file and should be applied first.

This reverts commit ad3d13eebef882b01494ce7d6e89628ff64b8e60.

* enigma2: fix build with musl

fixes:
 lib/base/thread.cpp:59:5: error: 'struct sched_param' has no member named '__sched_priority';
 lib/base/e2avahi.cpp:154:37: error: missing sentinel in function call [-Werror=format=]
 lib/dvb/epgcache.cpp:400:2: error: 'PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP' was not declared in this scope;
 lib/dvb/epgtransponderdatareader.cpp:10:65: error: 'PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP' was not declared in this scope;
 lib/gdi/gpixmap.cpp:9:2: error: #error "no BYTE_ORDER defined!"
 lib/gdi/font.cpp:35:31: error: 'PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP' was not declared in this scope;
 lib/gdi/pixmapcache.h:11:9: error: 'uint' does not name a type; did you mean 'rint'?
 lib/gdi/pixmapcache.cpp:134:30: error: 'MaximumSize' was not declared in this scope
 lib/gdi/font.cpp:35:31: error: 'PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP' was not declared in this scope;
 lib/gdi/pixmapcache.h:11:9: error: 'uint' does not name a type; did you mean 'rint'?
 lib/gdi/pixmapcache.cpp:8:1: error: 'uint' does not name a type; did y
 lib/gdi/pixmapcache.cpp:134:30: error: 'MaximumSize' was not declared

 Plugins/Extensions/SocketMMI/src/socket_mmi.cpp:1:
 ...../usr/include/sys/poll.h:1:2: error: #warning redirecting incorrect
  include <sys/poll.h> to <poll.h> [-Werror=cpp]

lib/gdi/font.cpp:35:31: error: 'PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP' was not declared in this scope;
main/bsod.cpp:6:10: fatal error: execinfo.h: No such file or directory
main/enigma.cpp:357:18: error: variable 'dump_malloc_stats()::mallinfo mi' has initializer but incomplete type
main/enigma.cpp:357:32: error: invalid use of incomplete type 'struct dump_malloc_stats()::mallinfo'

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>
Signed-off-by: persianpros <persianpros@yahoo.com>

Co-authored-by: Andrea Adami <andrea.adami@gmail.com>
(cherry picked from commit c0e796060aaf5be2eebedcf874c4c7d6b2c73871)