[ConfigList] add sanity check in getCurrentValue
File "/usr/lib/enigma2/python/Components/ConfigList.py", line 187, in
getCurrentValue
IndexError: tuple index out of range

(cherry picked from commit 0a611f3830959a724e2567d9428f4605cb852bd0)