[VirtualKeyBoard] add sanity check
Traceback (most recent call last):
File "/usr/lib/enigma2/python/Tools/NumericalTextInput.py", line 242, in
timeout
self.nextChar()
File "/usr/lib/enigma2/python/Tools/NumericalTextInput.py", line 247, in
nextChar
self.nextFunction()
File "/usr/lib/enigma2/python/Screens/VirtualKeyBoard.py", line 875, in
smsGotChar
if self.smsChar and self.selectAsciiKey(self.smsChar):
AttributeError: 'VirtualKeyBoard' object has no attribute 'smsChar'

(cherry picked from commit 291720aa881e87f77fce4053260fb1acb1a1fa52)