Scanner.py: Fix scanner is NoneType
 File "/usr/lib/enigma2/python/Components/Scanner.py", line 175, in scanDevice
    paths_to_scan.update(set(s.paths_to_scan))
AttributeError: 'NoneType' object has no attribute 'paths_to_scan'

I can't use fnc, so I have to use __call__.

(cherry picked from commit c2215a5fecab85fd38e168e968a5e6364a3b42b1)