PyInt_FromLong -> PyLong_FromLong
Remove duplicate PyInt_FromLong macro definitions.

 In file included from ../../git/lib/python/connections.h:6,
|                  from ../../git/lib/base/ebase.h:20,
|                  from python/enigma_python.cpp:3363:
| ../../git/lib/python/python.h:440: error: "PyInt_FromLong" redefined [-Werror]
|   440 | #define PyInt_FromLong(val) Impl_PyInt_FromLong(val)
|       |
| python/enigma_python.cpp:777: note: this is the location of the previous definition
|   777 | #define PyInt_FromLong(x) PyLong_FromLong(x)

(cherry picked from commit 12763c3290b01e903b01800ff6af58ab9e673529)