PositionerSetup: Fix crash
 File "/usr/lib/enigma2/python/StartEnigma.py", line 272, in doInstantiateDialog
    dlg = screen(self, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/PositionerSetup/ui.py", line 175, in __init__
  File "/usr/lib/enigma2/python/Components/TuneTest.py", line 14, in tune
TypeError: in method 'eDVBFrontendParametersSatellite_frequency_set', argument 2 of type 'unsigned int'

File "/usr/lib/enigma2/python/Components/GUIComponent.py", line 106, in GUIcreate
    self.postWidgetCreate(self.instance)
  File "/usr/lib/enigma2/python/Components/TunerInfo.py", line 138, in postWidgetCreate
    instance.setValue(self.value)
TypeError: in method 'eSlider_setValue', argument 2 of type 'int'

(cherry picked from commit 61fdf9fdef1ff5ae1d5db2c0482486d634300b33)