[ChannelSelection] add sanity check for getCurrentSelectionName (#3534)
File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 369, in
removeEntry
File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 360, in
getCurrentSelectionName
AttributeError: 'NoneType' object has no attribute 'getName'

(cherry picked from commit dae0291aebc0bfb3a39dcc7a9791110171dcad32)