AutoDiseqc.py: Don't call getConfigListEntry()
Due to Python optimization build-env, -assert- statement doesn't work.
Also, calling a function with one argument what checks if there is more
than one argument is superfluous.

Fix crash with working assert:

File "/usr/lib/enigma2/python/Screens/AutoDiseqc.py", line 514, in tunerStopScan
    self.list.append(getConfigListEntry((_("DiSEqC port %s: %s") % (x[0], x[2]))))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Components/config.py", line 1919, in getConfigListEntry
    assert len(args) > 1, "getConfigListEntry needs a minimum of two arguments (descr, configElement)"
           ^^^^^^^^^^^^^
AssertionError: getConfigListEntry needs a minimum of two arguments (descr, configElement)

(cherry picked from commit 2a7d8186a37aebbd093ea6ce0f42dd42ce1926a1)