Text blending (#4069)
* [Added] text blending functionality
* most of the code is taken from OpenATV.
* Credits to @jblayel

e.g. <widget source="myText" render="Label" alphatest="blend" ... />

* [Updated]  Adjust addons to respect new text blending possibilities

* [font.cpp] attempt to fix build error...

PLi compiler is old and not compatible with "register" keyword. Please revert when the compiler is updated.

error: ISO C++17 does not allow ‘register’ storage class specifier [-Werror=register]

---------

Co-authored-by: Dimitar Tsenev <dimitar_tsenev@outlook.com>
(cherry picked from commit 143341499d54689c49588f98a1b729b1adb25a39)