[VariableValue] sanity check int value (#3390)
File "/usr/lib/enigma2/python/Components/VariableValue.py", line 11, in
setValue
OverflowError: in method 'eSlider_setValue', argument 2 of type
'int'

(cherry picked from commit 381a2cda69a5cf8ff3ba971a5a94b06fa03a0a20)