[VariableText] sanity check text 'str' type
File "/usr/lib/enigma2/python/Components/VariableText.py", line 12, in
setText
TypeError: in method 'eLabel_setText', argument 2 of type 'std::string
const &'

same as:

https://github.com/OpenPLi/enigma2/commit/71e46a137bab62909bc3ad79530896c433aca883
(cherry picked from commit 766708e677cda7a69b77b7ece42276c6cb675530)