epgcache: fix build when using CI
This commit fixes the following error:
dvb/epgcache.cpp:2208:46: error: cannot convert ‘int*’ to ‘Py_ssize_t*’ {aka ‘long int*’}

(cherry picked from commit a4e45fcc820e76fc39c14aa5cc9d245400c91110)