[ScanSetup] sanity check empty slot (#3730)
root@dm8000:/hdd# cat /proc/bus/nim_sockets
NIM Socket 0:
Type: DVB-S2
Name: BCM4506 (internal)
Has_Outputs: no
Frontend_Device: 0
I2C_Device: 3
NIM Socket 1:
Type: DVB-S2
Name: BCM4506 (internal)
Has_Outputs: no
Frontend_Device: 1
I2C_Device: 3
NIM Socket 2:
empty
NIM Socket 3:
empty

File "/usr/lib/enigma2/python/Screens/ScanSetup.py", line 1007, in
<listcomp>
TypeError: 'NoneType' object is not subscriptable

(cherry picked from commit a1fd294dedcf16806aa49a48f2643ebb8cd32107)