[dvbci_ccmgr.cpp] Fix build against OpenSSL 4.0.0
Although even Wrynose still on OpenSSL 3.5.6, it's harmless to apply this
tiny patch now for future update OpenSSL.

Fix:

| ../../sources/enigma2-3.14+git/lib/dvb_ci/dvbci_ccmgr.cpp:993:40: error: invalid conversion from 'const X509_NAME*'
            {aka 'const X509_name_st*'} to 'X509_NAME*' {aka 'X509_name_st*'} [-fpermissive]
|       |         subject = X509_get_subject_name(cert);
|       |                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~
|       |                                        |
|       |                                        const X509_NAME* {aka const X509_name_st*}

(cherry picked from commit 3ae39f72fe82d5e910b1110a59eebe75ae0e6fe2)