AVSwitch: allow importing iAVSwitch (#3914)
This commit allows to import name 'iAVSwitch' from 'Components.AVSwitch'

Plugin IPTVPlayer was failing with the following error:
Plugin  Extensions/IPTVPlayer failed to load: cannot import name 'iAVSwitch' from 'Components.AVSwitch' (/usr/lib/enigma2/python/Components/AVSwitch.py)
ImportError: cannot import name 'iAVSwitch' from 'Components.AVSwitch' (/usr/lib/enigma2/python/Components/AVSwitch.py)

Declaring the iAVSwitch prior calling InitAVSwitch fixes the error.

(cherry picked from commit f2e0f2596503d1cb2a3f976f1ff33426a5184477)