TimerEdit.py: Fix 'cmp' invalid keyword argument for sort
  self.createGUIScreen(self.instance, self.desktop)
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 272, in createGUIScreen
    f()
  File "/usr/lib/enigma2/python/Screens/TimerEdit.py", line 259, in fillTimerList
    self.list.sort(cmp=eol_compare)
TypeError: 'cmp' is an invalid keyword argument for sort()

(cherry picked from commit 3be792eeaba2062d064d7472a502ca4a1238a133)