[ScanSetup] fix str py3
File "/usr/lib/enigma2/python/Screens/ScanSetup.py", line 448, in
getTerrestrialTransponderData
TypeError: can only concatenate str (not
"bytes") to str

(cherry picked from commit 0b338d0002ac2911d641cfa2cc208f8f93c3a838)