Console: Solve GSOD when system call was interrupted
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/Harddisk.py", line 480, in runIdle
    self.setSleep()
  File "/usr/lib/enigma2/python/Components/Harddisk.py", line 485, in setSleep
    Console().ePopen(("sdparm", "sdparm", "--flexible", "--readonly", "--command=stop", self.disk_path))
  File "/usr/lib/enigma2/python/Components/Console.py", line 49, in ePopen
    return ConsoleItem(self.appContainers, cmd, callback, extra_args)
  File "/usr/lib/enigma2/python/Components/Console.py", line 27, in __init__
    os.waitpid(self.container.getPID(), 0)
OSError: [Errno 4] Interrupted system call

(cherry picked from commit 1ba73d299fd3f8da033b5a75cae90353efd1ab32)