PositionerSetup: Fix crash fine movement
File "/usr/lib/enigma2/python/Plugins/SystemPlugins/PositionerSetup/ui.py", line 571, in dots
    return (s / 10) * '.' if s < 100 else 10 * '.'
TypeError: can't multiply sequence by non-int of type 'float'

(cherry picked from commit 6a2d05912ee28f871108555ec19d6db3a777e8e1)