[lib/dvb/lowlevel] Add names to anonymous non-C-compatible type
Fix build with GCC-16.

| ../../sources/enigma2-3.14+git/lib/dvb/lowlevel/mhw.h:44:16: error: anonymous non-C-compatible
 type given name for linkage purposes by 'typedef' declaration [-Werror=non-c-typedef-for-linkage]
|    44 | typedef struct {
|       |                ^
|       |                mhw_title_t

| ../../sources/enigma2-3.14+git/lib/dvb/lowlevel/eit.h:35:16: error: anonymous non-C-compatible
 type given name for linkage purposes by 'typedef' declaration [-Werror=non-c-typedef-for-linkage]
|    35 | typedef struct {
|       |                ^
|       |                eit_t

(cherry picked from commit 204933b093dc5d63753ce409d85c4badb615f342)