python.h: Remove duplicate definition of Impl_PyLong_FromLong()
                 from ../../../../../../../git/lib/python/Plugins/Extensions/SocketMMI/src/socket_mmi.h:5,
|                  from ../../../../../../../git/lib/python/Plugins/Extensions/SocketMMI/src/socket_mmi.cpp:1:
| ../../../../../../../git/lib/python/python.h:366:18: error: redefinition of 'ePyObject Impl_PyLong_FromLong(long int)'
|   366 | inline ePyObject Impl_PyLong_FromLong(long val)
|       |                  ^~~~~~~~~~~~~~~~~~~~
| ../../../../../../../git/lib/python/python.h:357:18: note: 'ePyObject Impl_PyLong_FromLong(long int)' previously defined here
|   357 | inline ePyObject Impl_PyLong_FromLong(long val)
|       |                  ^~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 4b81ba2339f35b93f2fd169e1c574de328119f1f)