Fix MenuList initialize in FIFOList
This fix AttributeError: 'FIFOList' object has no attribute 'l' after https://github.com/OpenPLi/enigma2/commit/fb23b131cebce07c4ae7c08b5d7ec4801c238754
Thx Amai for report.

(cherry picked from commit 008a4d487ebc5479a1a20ce0c31c1f51ce571af9)