[AudioSelection] fix selected_subtitle for some plugins (#3065)
-File "/usr/lib/enigma2/python/Screens/AudioSelection.py", line 239, in
getSubtitleList
AttributeError: 'RemotePlayer' object has no attribute
'selected_subtitle'

(cherry picked from commit 40f8bf58771ef2321d32d7d4f96e7c6da4fcb494)