[Satfinder] add more config if not sat list
File
"/usr/lib/enigma2/python/Plugins/SystemPlugins/Satfinder/plugin.py",
line 164, in createSetup
ValueError: invalid literal for int() with base
10: ''

(cherry picked from commit 9494777ba30b946a74ce7811f508b787c21a02e7)