[Screen] addSummary/removeSummary add sanity check (#3560)
File "/usr/lib/enigma2/python/StartEnigma.py", line 251, in execEnd
self.current_dialog.removeSummary(self.summary)
File "/usr/lib/enigma2/python/Screens/Screen.py", line 287, in
removeSummary
self.summaries.remove(summary)
ValueError: list.remove(x): x not in list

(cherry picked from commit 998228b7c1c771ef0e3ead9750d0c4ef13e4f2c4)