[Satconfig] sanity check when open tuner setup (#3388)
File "/usr/lib/enigma2/python/Screens/Satconfig.py", line 809, in
okbuttonClick
AttributeError: 'bool' object has no attribute 'slot'

(cherry picked from commit 4cf2ad3c93680791dc065098aeaec5f28fef9daf)