Resolve GSOD for power button when power buttin is assgined to powermenu
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
  File "/usr/lib/enigma2/python/StartEnigma.py", line 369, in powerup
    self.doAction(config.misc.hotkey.power.value)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 394, in doAction
    menu_screen = self.session.openWithCallback(self.MenuClosed, MainMenu, x)
AttributeError: 'PowerKey' object has no attribute 'MenuClosed'
[ePyObject] (CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap object at 0xb2e34988>>,('GlobalActions', 'power_up')) failed)

See: https://forums.openpli.org/topic/99136-hotkey-enigma-crash/
(cherry picked from commit 7856531e543dc9902d113b1e9da459674e8d3346)