EpgList.py: Percent must be an integer (Python 3.10)
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/EpgList.py", line 274, in buildMultiEntry
    clock_types = self.getClockTypesForEntry(service, eventId, beginTime, duration)
TypeError: 'float' object cannot be interpreted as an integer
[eListboxPythonMultiContent] error getting item 19
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/Sources/Clock.py", line 22, in poll
    self.changed((self.CHANGED_POLL,))
TypeError: 'float' object cannot be interpreted as an integer

(cherry picked from commit 10389a38ddc81ff1bf5845a93d2169106019f234)