[gpixmap.cpp] Drop unused variable 'backColor'
Fix build with GCC-16.

| ../../sources/enigma2-3.14+git/lib/gdi/gpixmap.cpp: In member function 'void gPixmap::drawRectangle(const gRegion&,
const eRect&, const gRGB&, const gRGB&, int, const std::vector<gRGB>&, uint8_t, int, uint8_t, bool, int)':
| ../../sources/enigma2-3.14+git/lib/gdi/gpixmap.cpp:468:18: error: variable 'backColor' set but not used
 [-Werror=unused-but-set-variable=]
|   468 |         uint32_t backColor = backgroundColor.argb();
|       |                  ^~~~~~~~~

(cherry picked from commit 91a7a425354c5a171cbb8e804807f5606078d0ad)