[MovieSelection] fix delete record.stream (#3565)
File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 2509, in
confirm
  File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py",
line 2502, in moveToTrash
  File
"/usr/lib/enigma2/python/Screens/MovieSelection.py", line 187, in
moveServiceFiles
FileNotFoundError: [Errno 2] No such file or directory:
'/media/hdd/movie/20221119 1634 - instant record.ts' ->
'/media/hdd/movie/.Trash/20221119 1634 - instant record.ts'

-thanks OpenVisionE2  team

(cherry picked from commit 77f692b344b4e17b1bbf42a55d292696accdd54f)