[SoftcamSetup] fix cardserver (#4030)
File "/usr/lib/enigma2/python/Screens/SoftcamSetup.py", line 38, in
__init__
AttributeError: 'SoftcamSetup' object has no attribute 'server'

(cherry picked from commit 4d99960cbfb7339dcc006dacb5a7f43fbea65008)